'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Map,UserRound,Backpack,PawPrint,Save,X,Send,Volume2,VolumeX,Plus,Minus,BookOpen,HelpCircle,ChevronRight,Footprints,Music2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Progress} from '@/components/ui/progress';
import {SIZE,REGIONS,ITEMS,WEAPONS,partyDogs,entities,type GameState,type Action} from '@/lib/game/model';
import TravelerPreview from './traveler-preview';
import {MAP_FRAMES} from '@/lib/game/maps';
export type AdventureMessage={id:string;text:string;author:string;time:string;kind:'system'|'memo'};
type Layer='chat'|'map'|'status';
type OpenPanel='wardrobe'|'map'|'bag'|'dogs'|'journal'|'save'|'help';
export default function AdventureHUD({state,messages,notice,onMessage,onAction,onOpen,zoom,onZoom,running,onRunning,sound,onSound,music,onMusic,musicLabel,saveStatus}:{state:GameState;messages:AdventureMessage[];notice:string;onMessage:(text:string)=>void;onAction:(a:Action)=>unknown;onOpen:(p:OpenPanel)=>void;zoom:number;onZoom:(n:number)=>void;running:boolean;onRunning:()=>void;sound:boolean;onSound:()=>void;music:boolean;onMusic:()=>void;musicLabel:string;saveStatus:string}){
 const [layer,setLayer]=useState<Layer|null>(null),[draft,setDraft]=useState(''),[name,setName]=useState(state.playerName),[lastRead,setLastRead]=useState('');const log=useRef<HTMLDivElement>(null);
 const latest=messages.at(-1),unread=!!latest&&latest.id!==lastRead,party=partyDogs(state),region=REGIONS[state.region];
 useEffect(()=>setName(state.playerName),[state.playerName]);
 useEffect(()=>{if(layer==='chat'){setLastRead(latest?.id??'');if(log.current)log.current.scrollTop=log.current.scrollHeight;}},[layer,latest?.id]);
 const toggle=(next:Layer)=>setLayer(old=>old===next?null:next);
 const indoors=state.place==='shop',[fw,fh]=indoors?[1254,1254]:MAP_FRAMES[state.region];
 return <div className="adventure-hud">
  <div className="field-hud-top"><button className="traveler-badge" onClick={()=>toggle('status')} aria-label="플레이어 상태와 이름 변경"><UserRound size={18}/><strong>{state.playerName}</strong></button><button className="location-badge" onClick={()=>toggle('map')}><Map size={16}/><span>{indoors?'여행 상점':region.name}</span></button><span className="wallet-badge">◈ {state.coins.toLocaleString()}</span></div>
  {!layer&&notice&&!state.battle&&<button className="message-peek" onClick={()=>setLayer('chat')} aria-label="메시지 기록 열기"><MessageCircle size={16}/><span>{notice}</span></button>}
  {layer&&<section data-game-input className={`hud-layer ${state.battle?'over-battle':''}`} aria-label="메시지 지도 상태 레이어"><div className="hud-layer-head"><Tabs value={layer} onValueChange={v=>setLayer(v as Layer)}><TabsList><TabsTrigger value="chat">메시지</TabsTrigger><TabsTrigger value="map">미니맵</TabsTrigger><TabsTrigger value="status">상태</TabsTrigger></TabsList></Tabs><button className="close-layer" onClick={()=>setLayer(null)} aria-label="레이어 닫기"><X size={19}/></button></div>
   {layer==='chat'&&<><div className="chat-tools"><button onClick={()=>onOpen('help')}><HelpCircle size={14}/>도움말</button><button onClick={()=>onOpen('journal')}><BookOpen size={14}/>모험 일지</button></div><div className="adventure-chat" ref={log} role="log" aria-label="모험 메시지">{messages.map(m=><div className={`chat-line ${m.kind}`} key={m.id}><div><strong>{m.author}</strong><time>{m.time}</time></div><p>{m.text}</p></div>)}</div><form className="chat-compose" onSubmit={e=>{e.preventDefault();if(!draft.trim())return;onMessage(draft.trim());setDraft('');}}><Input aria-label="모험 메모" placeholder="모험 메모 남기기" value={draft} maxLength={300} onChange={e=>setDraft(e.target.value)}/><button type="submit" disabled={!draft.trim()} aria-label="메모 남기기"><Send size={18}/></button></form></>}
   {layer==='map'&&<div className="hud-layer-body"><div className="mini-map-heading"><strong>{indoors?'여행 상점':region.name}</strong><span>{indoors||state.region===1?'안전 지역':'전투 지역'}</span></div><div className="layer-minimap" role="img" aria-label={`${region.name} 미니맵. 노란 점은 내 위치, 붉은 점은 적입니다.`} style={{backgroundImage:`url(${indoors?'/art/shop-interior.png':`/art/regions/${state.region}.png`})`,backgroundSize:`${1254/fw*100}% ${1254/fh*100}%`}}>{entities(state).filter(e=>['enemy','shop','exit','merchant'].includes(e.kind)).map(e=><i key={e.id} className={`map-marker ${e.kind}`} style={{left:`${e.x/SIZE*100}%`,top:`${e.y/SIZE*100}%`}}/>)}<i className="map-marker player" style={{left:`${state.x/SIZE*100}%`,top:`${state.y/SIZE*100}%`}}/></div><div className="minimap-legend"><span>● 내 위치</span><span>● 적</span><span>● 상점</span></div><button className="layer-wide-button" onClick={()=>onOpen('map')}>세계 지도 열기<ChevronRight size={16}/></button></div>}
   {layer==='status'&&<div className="hud-layer-body"><form className="name-editor" onSubmit={e=>{e.preventDefault();onAction({type:'rename',name});e.currentTarget.querySelector('input')?.blur();}}><label htmlFor="traveler-name">내 이름</label><div><Input id="traveler-name" value={name} maxLength={12} onChange={e=>setName(e.target.value)}/><button type="submit" disabled={!name.trim()||name===state.playerName}>변경</button></div></form><button className="wardrobe-entry" disabled={!!state.battle} onClick={()=>onOpen('wardrobe')}><TravelerPreview appearance={state.appearance} size={76}/><span><strong>외모·옷 꾸미기</strong><small>{state.battle?'전투가 끝나면 변경할 수 있어요':'얼굴 · 머리 · 옷 · 색상'}</small></span><ChevronRight size={18}/></button><div className="status-weapon"><span>장착 무기</span><strong>{state.weapon?`${ITEMS[state.weapon].name} +${WEAPONS[state.weapon].attack}`:'맨손'}</strong></div><div className="status-party-heading"><strong>동행 {party.length} / 2</strong><button onClick={()=>onOpen('dogs')}>편성<ChevronRight size={14}/></button></div>{party.map((dog,i)=><div className="status-companion" key={dog.id}><div><PawPrint size={16}/><strong>{dog.name}</strong><small>{i===0?'선두':'지원'} · Lv.{dog.level}</small></div><Progress value={dog.hp/dog.maxHp*100}/><span>HP {dog.hp} / {dog.maxHp} · 공격 {dog.atk}</span></div>)}{party.length<2&&<button className="empty-party-slot" onClick={()=>onOpen('dogs')}><Plus size={16}/>두 번째 동료 선택</button>}<div className="status-controls"><button aria-pressed={running} onClick={onRunning}><Footprints size={17}/>{running?'달리기':'걷기'}</button><button aria-pressed={sound} onClick={onSound} aria-label={sound?'효과음 끄기':'효과음 켜기'}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}효과음</button><button aria-label="화면 축소" disabled={zoom<=.49} onClick={()=>onZoom(Math.max(.49,zoom-.12))}><Minus size={17}/></button><button aria-label="화면 확대" disabled={zoom>=1.1} onClick={()=>onZoom(Math.min(1.1,zoom+.12))}><Plus size={17}/></button></div><button className="layer-wide-button music-control" aria-pressed={music} onClick={onMusic}><Music2 size={17}/><span>배경음<small>{musicLabel}</small></span><b>{music?'ON':'OFF'}</b></button><button className="layer-wide-button" onClick={()=>onOpen('save')}><Save size={16}/>{saveStatus}<ChevronRight size={16}/></button></div>}
  </section>}
  <nav className="touch-navigation" aria-label="게임 메뉴"><button aria-pressed={layer==='chat'} onClick={()=>toggle('chat')}><span><MessageCircle/>{unread&&<i/>}</span>메시지</button><button aria-pressed={layer==='map'} onClick={()=>toggle('map')}><Map/>미니맵</button><button aria-pressed={layer==='status'} onClick={()=>toggle('status')}><UserRound/>상태</button><button onClick={()=>onOpen('bag')}><Backpack/>가방</button><button onClick={()=>onOpen('dogs')}><PawPrint/>동료</button><button onClick={()=>onOpen('save')}><Save/>저장</button></nav>
 </div>;
}
