'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {PawPrint,Map,Backpack,BookOpen,Save,Sun,Compass,ArrowUpRight,ChevronRight,Plus,Minus,Volume2,VolumeX,HelpCircle,Check,Coins,Download,Upload,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Swords,Shield,Flag,Navigation,Package,FolderOpen} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {newGame,currentDog,REGIONS,BREEDS,ITEMS,act,nearest,countItem,packSave,unpackSave,type GameState,type Action} from '@/lib/game/model';
import World from './world';
type Panel='map'|'bag'|'dogs'|'journal'|'save'|'shop'|'help'|null;
type SaveMeta={slot:number;name:string;date:string;region:string;dogs:number}|null;
function Portrait({sprite,size=120}:{sprite:number;size?:number}){return <div className="portrait" role="img" aria-label={sprite===0?'여행자':sprite===7?'목줄단':BREEDS.find(b=>b.sprite===sprite)?.name} style={{width:size*.75,height:size,backgroundSize:`${size*3}px ${size*2}px`,backgroundPosition:`-${sprite%4*size*.75}px -${Math.floor(sprite/4)*size}px`}} />;}
export default function Home(){
 const [state,setState]=useState<GameState>(newGame);const game=useRef(state);const [panel,setPanel]=useState<Panel>(null);const paused=useRef(false);const moveKeys=useRef(new Set<string>());const [notice,setNotice]=useState('');const [welcome,setWelcome]=useState(true);const [zoom,setZoom]=useState(.74);const [sound,setSound]=useState(false);const soundRef=useRef(false);const audioRef=useRef<AudioContext|null>(null);const [saveStatus,setSaveStatus]=useState('자동 저장 대기');const [saves,setSaves]=useState<SaveMeta[]>([null,null,null]);const [overwrite,setOverwrite]=useState<number|null>(null);const [bagFilter,setBagFilter]=useState('all');const [selectedItem,setSelectedItem]=useState<number|null>(0);const [burst,setBurst]=useState('');const [ready,setReady]=useState(false);const inputFile=useRef<HTMLInputElement>(null);const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const burstTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const write=useCallback((s:GameState)=>{game.current=s;setState({...s});},[]);
 const tell=useCallback((text:string)=>{if(!text)return;setNotice(text);if(noticeTimer.current)clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),4500);},[]);
 const beep=useCallback((kind:string)=>{if(!soundRef.current)return;try{const ac=audioRef.current??new AudioContext();audioRef.current=ac;void ac.resume();const frequencies=kind==='win'?[523,659,784]:kind==='recruit'?[659,784,1047]:kind==='attack'?[220,165]:[440];frequencies.forEach((f,i)=>{const o=ac.createOscillator(),g=ac.createGain();o.type='triangle';o.frequency.value=f;o.connect(g);g.connect(ac.destination);g.gain.setValueAtTime(.055,ac.currentTime+i*.11);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+i*.11+.16);o.start(ac.currentTime+i*.11);o.stop(ac.currentTime+i*.11+.18);});}catch{}},[]);
 const dispatch=useCallback((a:Action)=>{const r=act(game.current,a);write(r.state);tell(r.message);if(r.event==='shop')setPanel('shop');if(r.event){beep(r.event);setBurst(r.event);if(burstTimer.current)clearTimeout(burstTimer.current);burstTimer.current=setTimeout(()=>setBurst(''),1100);}return r;},[write,tell,beep]);
 const tick=useCallback(()=>setState({...game.current}),[]);
 const open=useCallback((p:Panel)=>{if(game.current.battle&&p!=='dogs'&&p!=='bag'){tell('전투를 마친 뒤 열 수 있어요.');return;}setPanel(p);setOverwrite(null);setWelcome(false);moveKeys.current.clear();},[tell]);
 paused.current=!!panel||welcome;const d=currentDog(state);const region=REGIONS[state.region];const near=nearest(state);const bagUsed=state.bag.filter(Boolean).length;const captains=state.defeated.filter(id=>id.startsWith('captain-')).length;
 const readSaveList=useCallback(()=>{try{setSaves([0,1,2].map(i=>{const raw=localStorage.getItem(`tails-city-slot-${i}`);if(!raw)return null;const s=unpackSave(raw);return {slot:i,name:currentDog(s).name,date:JSON.parse(raw).savedAt,region:REGIONS[s.region].name,dogs:s.dogs.length};}));}catch{tell('일부 저장 데이터를 읽을 수 없어요. 파일 저장본을 열어 주세요.');}},[tell]);
 useEffect(()=>{try{const raw=localStorage.getItem('tails-city-auto');if(raw){write(unpackSave(raw));setWelcome(false);setSaveStatus('자동 저장 불러옴');}}catch{tell('자동 저장을 읽지 못했어요. 새 모험으로 시작합니다.');}readSaveList();setReady(true);return()=>{if(noticeTimer.current)clearTimeout(noticeTimer.current);if(burstTimer.current)clearTimeout(burstTimer.current);};},[write,tell,readSaveList]);
 useEffect(()=>{if(!ready)return;const auto=()=>{if(game.current.battle)return;try{localStorage.setItem('tails-city-auto',packSave(game.current));setSaveStatus('자동 저장됨');}catch{setSaveStatus('자동 저장 실패 · 파일 저장 권장');}};const t=setInterval(auto,15000);window.addEventListener('pagehide',auto);return()=>{clearInterval(t);window.removeEventListener('pagehide',auto);};},[ready]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;const k=e.key.toLowerCase();const panels:Record<string,Panel>={b:'bag',i:'bag',m:'map',p:'dogs',j:'journal'};if(panels[k]&&!e.metaKey&&!e.ctrlKey){e.preventDefault();open(panel===panels[k]?null:panels[k]);}if(k==='escape'){setPanel(null);setWelcome(false);}if(e.ctrlKey&&k==='s'){e.preventDefault();open('save');}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[panel,open]);
 // A small optional WebMCP surface shares the exact inventory and save actions used by the UI.
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_adventure',description:'현재 지역, 동료, 가방과 전투 상태를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({region:REGIONS[game.current.region].name,dogs:game.current.dogs,capacity:game.current.capacity,coins:game.current.coins,battle:game.current.battle})},{name:'open_adventure_panel',description:'게임의 세계 지도, 가방, 동료 또는 저장 창을 엽니다.',inputSchema:{type:'object',properties:{panel:{type:'string',enum:['map','bag','dogs','save']}},required:['panel'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const p=(input as {panel?:Panel})?.panel;if(!p||!['map','bag','dogs','save'].includes(p))throw Error('올바른 창을 선택하세요.');if(game.current.battle&&!['bag','dogs'].includes(p))throw Error('전투를 먼저 마치세요.');open(p);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {opened:p};}}];for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[open]);
 function manualSave(slot:number){if(saves[slot]&&overwrite!==slot){setOverwrite(slot);return;}try{localStorage.setItem(`tails-city-slot-${slot}`,packSave(game.current));readSaveList();setOverwrite(null);tell(`저장 칸 ${slot+1}에 모험을 저장했어요.`);}catch{tell('저장 공간이 부족하거나 브라우저 저장이 차단되었어요. 파일로 저장해 주세요.');}}
 function loadSave(slot:number){try{const raw=localStorage.getItem(`tails-city-slot-${slot}`);if(!raw)throw Error('저장 파일이 없어요.');write(unpackSave(raw));setPanel(null);setWelcome(false);tell('모험을 불러왔어요.');}catch(e){tell(e instanceof Error?e.message:'불러오지 못했어요.');}}
 function exportSave(){const blob=new Blob([packSave(game.current)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`tails-city-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);tell('모험을 파일로 저장했어요.');}
 async function importSave(file:File|undefined){if(!file)return;try{if(file.size>200000)throw Error('200KB 이하의 저장 파일을 선택해 주세요.');const s=unpackSave(await file.text());write(s);setPanel(null);setWelcome(false);tell('저장 파일을 열었어요.');}catch(e){tell(e instanceof Error?e.message:'파일을 열지 못했어요.');}if(inputFile.current)inputFile.current.value='';}
 const titles:Record<string,string>={map:'세계 지도',bag:'나의 가방',dogs:'우리의 동료들',journal:'모험 일지',save:'모험을 간직하기',shop:'길 위의 작은 상점',help:'여행자 안내서'};
 const selected=selectedItem===null?null:state.bag[selectedItem];const chapter=captains===6?'에필로그 · 다시, 산책':captains>0?'CHAPTER 02 · 이어지는 발자국':'CHAPTER 01 · 첫 번째 발자국';
 return <main className="app-shell"><header className="topbar"><button className="brand" onClick={()=>open(null)} aria-label="탐험 화면"><span className="brand-mark"><PawPrint size={26}/></span><span>TAILS CITY<small>우리의 발자국이 모험이 되는 곳</small></span></button><nav aria-label="게임 메뉴"><button className={!panel?'active':''} onClick={()=>open(null)}><Compass/>탐험</button><button className={panel==='map'?'active':''} onClick={()=>open('map')}><Map/>세계 지도</button><button className={panel==='bag'?'active':''} onClick={()=>open('bag')}><Backpack/>가방 <span className="nav-count">{bagUsed}</span></button><button className={panel==='dogs'?'active':''} onClick={()=>open('dogs')}><PawPrint/>동료</button><button className={panel==='journal'?'active':''} onClick={()=>open('journal')}><BookOpen/>모험 일지</button></nav><button className="save-button" onClick={()=>open('save')}><Save/>저장 / 불러오기</button></header>
 <section className="region-bar"><div><span className="eyebrow">{chapter}</span><h1>{region.name}<span>{state.region===0?'시작 지역':`권장 Lv. ${region.level}+`}</span></h1></div><div className="weather"><Sun size={20}/>{state.region===5?'밤':'맑음'} <b>{String(14+Math.floor(state.seconds/3600)%10).padStart(2,'0')}:{String(32+Math.floor(state.seconds/60)%28).padStart(2,'0')}</b><i/><span className="coin">◈</span><strong>{state.coins.toLocaleString()}</strong></div></section>
 <div className="game-layout"><section className="play-column"><div className={`playfield ${burst==='attack'?'attack-flash':''}`}><World game={game} paused={paused} onAction={dispatch} onTick={tick} zoom={zoom} moveKeys={moveKeys}/><div className="map-title"><Compass size={17}/><b>{region.name}</b><span>Lv. {region.level}–{region.level+2}</span></div><div className="map-tools"><button aria-label="축소" disabled={zoom<=.49} onClick={()=>setZoom(z=>Math.max(.49,z-.12))}><Minus size={16}/></button><button aria-label="확대" disabled={zoom>=1.1} onClick={()=>setZoom(z=>Math.min(1.1,z+.12))}><Plus size={16}/></button><span/><button aria-label={sound?'효과음 끄기':'효과음 켜기'} onClick={()=>{soundRef.current=!sound;setSound(!sound);if(!sound)beep('toggle');}}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button aria-label="조작 도움말" onClick={()=>open('help')}><HelpCircle size={16}/></button></div>
 {welcome&&<div className="welcome-note"><span>새로운 모험</span><h2>함께라서, 더 멀리.</h2><p>평범한 산책길에서 시작되는<br/>조금 특별한 우리들의 이야기.</p><button onClick={()=>{setWelcome(false);tell('WASD로 이동하세요. 가까운 강아지에게 E로 간식을 줄 수 있어요.');}}>콩이와 산책 시작 <ArrowUpRight size={18}/></button><button className="text-link" onClick={()=>open('save')}>저장한 모험 이어 하기</button></div>}
 {near&&!state.battle&&!welcome&&!panel&&<button className="interact-prompt" onClick={()=>dispatch({type:'interact',id:near.id})}><kbd>E</kbd><span>{near.name}</span>{near.kind==='dog'?'친구 되기':near.kind==='enemy'?'전투하기':near.kind==='rest'?'모두 회복':near.kind==='loot'?'열어 보기':'상점 열기'}<ChevronRight size={16}/></button>}
 {!welcome&&!state.battle&&<div className="mobile-pad"><div className="direction-pad">{[['w',ArrowUp],['a',ArrowLeft],['s',ArrowDown],['d',ArrowRight]].map(([key,Icon])=>{const I=Icon as typeof ArrowUp;return <button key={key as string} className={`dir-${key}`} aria-label={`${key} 방향 이동`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);moveKeys.current.add(key as string);}} onPointerUp={()=>moveKeys.current.delete(key as string)} onPointerCancel={()=>moveKeys.current.delete(key as string)} onLostPointerCapture={()=>moveKeys.current.delete(key as string)}><I size={19}/></button>;})}</div><button className="mobile-e" aria-label="상호작용" disabled={!near} onClick={()=>near&&dispatch({type:'interact',id:near.id})}>E</button></div>}
 <div className="field-caption"><span className="live-dot"/>{region.en} <span className="caption-divider">/</span>{state.steps.toLocaleString()} 걸음</div>
 {state.battle&&<div className="battle-screen"><div className="battle-label"><Swords size={17}/>야생의 용기 · TURN {state.battle.turn}</div><div className="enemy-stat"><div><strong>{state.battle.enemy.name}</strong><span>{state.battle.enemy.captain?'지역 대장':'검은 목줄단'}</span></div><Progress value={state.battle.enemy.hp/state.battle.enemy.maxHp*100}/><small>{state.battle.enemy.hp} / {state.battle.enemy.maxHp} HP</small></div><div className="battle-enemy"><Portrait sprite={7} size={260}/></div><div className="battle-dog"><Portrait sprite={BREEDS[d.breed].sprite} size={230}/></div><div className="battle-ally"><strong>{d.name}<span>Lv.{d.level}</span></strong><Progress value={d.hp/d.maxHp*100}/><small>{d.hp} / {d.maxHp} HP</small></div><div className="battle-bottom"><div className="battle-log" aria-live="polite">{state.battle.log.slice(-2).map((line,i)=><p key={i}>{line}</p>)}</div><div className="battle-actions"><button onClick={()=>dispatch({type:'attack'})}><Swords/>함께 공격<small>여행자 + 동료</small></button><button className="skill-button" disabled={state.battle.cooldown>0} onClick={()=>dispatch({type:'skill'})}><PawPrint/>{BREEDS[d.breed].skill}<small>{state.battle.cooldown?`${state.battle.cooldown}턴 후 사용`:'강력한 고유 기술'}</small></button><button onClick={()=>open('bag')}><Backpack/>아이템<small>회복 / 도시락</small></button><button onClick={()=>dispatch({type:'flee'})}><Flag/>물러나기<small>안전하게 후퇴</small></button></div></div></div>}
 {burst==='win'&&<div className="victory-banner">VICTORY! <span>함께 해냈어요</span></div>}{burst==='recruit'&&<div className="victory-banner"><PawPrint/> NEW FRIEND <span>우리의 모험에 온 걸 환영해!</span></div>}</div>
 <div className="controls"><span><kbd>W A S D</kbd>이동</span><span><kbd>E</kbd>대화 / 상호작용</span><span><kbd>Shift</kbd>달리기</span><span><Navigation size={12}/>길을 클릭해도 이동할 수 있어요</span></div></section>
 <aside className="right-panel"><section className="quest-panel"><div className="panel-heading"><span className="eyebrow">진행 중인 모험</span><BookOpen size={15}/></div><h2>{state.won?'다시 찾아온 평화':captains>0?'도시에 빛을 되찾자':'첫 번째 발자국'}</h2><p>{state.won?'우리가 함께 지킨 도시. 아직 만나지 못한 친구들이 기다리고 있어요.':'도시에 드리운 검은 목줄단의 그림자. 새로운 친구와 첫 단서를 찾아보자.'}</p>{[{label:'강변에서 새로운 친구 만나기',done:state.recruited.length>0},{label:'목줄단 정찰병 물리치기',done:state.defeated.length>0},{label:'다음 지역으로 여행하기',done:state.visited.length>1}].map((q,i)=><div className={`quest-line ${q.done?'done':''}`} key={q.label}><span>{q.done?<Check size={12}/>:i+1}</span>{q.label}</div>)}<button className="journal-link" onClick={()=>open('journal')}>모험 일지 보기<ArrowUpRight size={14}/></button></section>
 <section className="companion-panel"><div className="panel-heading"><h2>함께하는 동료</h2><button className="plain-icon" aria-label="동료 바꾸기" onClick={()=>open('dogs')}><PawPrint size={17}/></button></div><div className="dog-preview"><Portrait sprite={BREEDS[d.breed].sprite} size={155}/><span className="friend-heart">♥</span></div><div className="dog-name"><h3>{d.name}<small>{BREEDS[d.breed].name} · {BREEDS[d.breed].type}</small></h3><span>Lv.{d.level}</span></div><Progress value={d.hp/d.maxHp*100} aria-label={`${d.name} 체력`}/><div className="stat-line"><span>HP</span>{d.hp} / {d.maxHp}</div><div className="xp-row"><Progress value={d.xp/(d.level*45)*100} aria-label="성장 경험치"/><span>EXP {d.xp} / {d.level*45}</span></div><p className="dog-quote">{d.hp<d.maxHp*.3?'“잠깐 쉬었다 가면 안 될까?”':'“어디든 함께 갈 준비가 됐어!”'}</p></section>
 <button className="travel-card" onClick={()=>open('map')}><span className="travel-icon"><Map size={24}/></span><span><b>더 넓은 세상으로</b><small>{state.visited.length} / 6 지역 발견</small></span><ChevronRight size={18}/></button></aside></div>
 <footer><span>TAILS CITY <i>·</i> 여섯 지역, 하나의 이야기</span><span className="save-state"><span className="live-dot"/>{saveStatus}</span><span>나만의 속도로, 함께 걷는 모험.</span></footer>
 <div className={`notification ${notice?'show':''}`} role="status" aria-live="polite"><PawPrint size={18}/>{notice}</div>
 <Dialog open={!!panel} onOpenChange={o=>{if(!o)setPanel(null);}}><DialogContent className={`game-dialog ${panel==='map'?'map-dialog':''} ${panel==='bag'?'bag-dialog':''}`}><div className="dialog-heading"><span className="eyebrow">TAILS CITY · {panel==='map'?'EXPLORE THE WORLD':'YOUR ADVENTURE'}</span><DialogTitle className="dialog-title">{titles[panel||'help']}</DialogTitle><DialogDescription>{panel==='map'?'연결된 길로 새 지역을 발견하세요. 방문한 곳은 빠르게 돌아갈 수 있어요.':panel==='bag'?`${bagUsed} / ${state.capacity}칸 사용 중 · 같은 아이템은 한 칸에 9개까지 보관`:panel==='dogs'?`${state.dogs.length}마리의 친구 · 동료를 선택하면 함께 걷고 싸웁니다.`:panel==='save'?'이 브라우저에 저장하거나, 파일로 보관하고 다시 열 수 있어요.':panel==='shop'?'모험에 필요한 작은 준비. 현재 보유 코인 '+state.coins:panel==='journal'?'작은 발자국들이 모여 도시를 바꿉니다.':'첫 산책을 위한 몇 가지 안내'}</DialogDescription></div>
 {panel==='map'&&<><div className="world-map-grid">{REGIONS.map(r=><button key={r.id} className={`region-card ${r.id===state.region?'current':''} ${!state.visited.includes(r.id)?'undiscovered':''}`} onClick={()=>{const res=dispatch({type:'travel',region:r.id});if(res.state!==game.current||res.state.region===r.id&&state.visited.includes(r.id))setPanel(null);}}><div className="region-art" style={{backgroundPosition:`${r.id%3*50}% ${Math.floor(r.id/3)*100}%`}}/><span className="region-index">0{r.id+1}</span>{state.visited.includes(r.id)&&<span className="visited-badge">{r.id===state.region?'현재 위치':'발견함'}</span>}<div className="region-card-text"><small>{r.en}</small><h3>{r.name}</h3><span>{r.tag}<b>Lv.{r.level}+</b></span></div></button>)}</div><div className="map-legend"><span><i className="legend-dot"/>발견한 지역: 클릭해 빠른 이동</span><span>각 맵의 상하좌우 끝에서 연결 지역으로 이동</span></div><div className="route-guide"><Compass size={18}/><span>현재 연결된 길: {region.neighbors.map((n,i)=>n>=0?`${['북쪽','동쪽','남쪽','서쪽'][i]} ${REGIONS[n].name}`:'').filter(Boolean).join(' · ')}</span></div></>}
 {panel==='bag'&&<><div className="bag-toolbar"><Tabs value={bagFilter} onValueChange={v=>setBagFilter(String(v))}><TabsList><TabsTrigger value="all">전체</TabsTrigger><TabsTrigger value="heal">회복</TabsTrigger><TabsTrigger value="friend">친구 간식</TabsTrigger></TabsList></Tabs><span><Coins size={16}/>{state.coins}</span></div><div className="bag-layout"><div className="bag-grid">{state.bag.map((slot,i)=>{const dim=slot&&bagFilter!=='all'&&(bagFilter==='friend'?slot.item!=='treat':slot.item==='treat');return <button className={`bag-slot ${selectedItem===i?'selected':''} ${dim?'dim':''}`} key={i} onClick={()=>setSelectedItem(i)} aria-label={slot?`${i+1}번 칸 ${ITEMS[slot.item].name} ${slot.qty}개`:`${i+1}번 빈 칸`}><small>{String(i+1).padStart(2,'0')}</small>{slot&&<><span>{ITEMS[slot.item].icon}</span><b>{slot.qty}</b></>}</button>;})}</div><div className="item-details">{selected?<><div className="item-visual">{ITEMS[selected.item].icon}</div><h3>{ITEMS[selected.item].name}</h3><span className="item-tag">{selected.item==='treat'?'친밀도 아이템':'회복 아이템'}</span><p>{ITEMS[selected.item].desc}</p><span className="target-dog">사용 대상: {d.name} · HP {d.hp}/{d.maxHp}</span><button className="primary-button" onClick={()=>dispatch({type:'item',id:selected.item})}>{selected.item==='treat'?'사용 방법 보기':state.battle?'사용하기 · 1턴 소모':'사용하기'}</button></>:<div className="empty-item"><Backpack size={38}/><p>아이템을 선택하면<br/>자세히 볼 수 있어요.</p></div>}</div></div><div className="expand-box"><span><Backpack size={20}/><span><b>조금 더 큰 모험을 위한 가방</b><small>{state.capacity>=100?'최대 크기입니다.':'코인으로 5칸씩, 최대 100칸까지 확장할 수 있어요.'}</small></span></span><button disabled={state.capacity>=100||!!state.battle||state.coins<200+(state.capacity-25)*12} onClick={()=>dispatch({type:'expand'})}><Plus size={16}/>5칸 확장 <b>◈ {200+(state.capacity-25)*12}</b></button></div></>}
 {panel==='dogs'&&<div className="dogs-grid">{state.dogs.map(dog=><button className={`dog-card ${dog.id===state.active?'selected':''}`} key={dog.id} onClick={()=>dispatch({type:'switch',id:dog.id})}><div className="dog-card-top"><span>Lv.{dog.level}</span>{dog.id===state.active?<span className="following"><Check size={12}/>동행 중</span>:<span>{BREEDS[dog.breed].type}</span>}</div><Portrait sprite={BREEDS[dog.breed].sprite} size={150}/><h3>{dog.name}<small>{BREEDS[dog.breed].name}</small></h3><Progress value={dog.hp/dog.maxHp*100}/><div className="stat-line"><span>HP {dog.hp}/{dog.maxHp}</span><span>공격 {dog.atk}</span></div><div className="dog-skill"><PawPrint size={13}/>{BREEDS[dog.breed].skill}</div></button>)}<div className="new-friend"><PawPrint size={36}/><h3>다음 친구는 어디에?</h3><p>각 지역에는 두 마리의<br/>강아지가 기다리고 있어요.</p><span>친구 간식 {countItem(state,'treat')}개 보유</span></div></div>}
 {panel==='journal'&&<div className="journal-content"><div className="story-intro"><span>PROLOGUE</span><h3>사라진 목줄의 비밀</h3><p>현대의 해안 도시 솔빛시. 어느 날부터 강아지들이 사라지기 시작했다. 도시의 모든 강아지를 통제하려는 ‘검은 목줄단’의 계획을 멈추기 위해, 당신과 콩이는 산책길 너머로 첫발을 내딛는다.</p></div><div className="journal-stats"><span><b>{state.dogs.length}</b>함께하는 동료</span><span><b>{state.visited.length} / 6</b>발견한 지역</span><span><b>{captains} / 6</b>물리친 지역 대장</span></div><h3>도시에 빛을 되찾자</h3><p>각 지역의 북쪽 길에 있는 지역 대장을 쓰러뜨려 신호기를 끄세요. 다섯 신호기를 모두 끈 뒤 블랙테일 본부의 대장에게 도전할 수 있습니다.</p><div className="chapter-list">{REGIONS.map(r=><div key={r.id}><span className={state.defeated.includes(`captain-${r.id}`)?'chapter-done':''}>{state.defeated.includes(`captain-${r.id}`)?<Check size={16}/>:r.id+1}</span><div><h4>{r.tag}<small>{r.name}</small></h4><p>{r.desc}</p></div><Shield size={18}/></div>)}</div>{state.won&&<div className="ending"><PawPrint/><h3>이 도시의 모든 발자국을 위해.</h3><p>검은 목줄단은 해체되었고 강아지들이 집으로 돌아왔습니다. 당신과 친구들의 산책은 계속됩니다.</p></div>}</div>}
 {panel==='save'&&<><div className="save-slots">{[0,1,2].map(i=><div className="save-slot" key={i}><span className="slot-number">0{i+1}</span><div><h3>{saves[i]?saves[i]!.region:'아직 쓰지 않은 이야기'}</h3><p>{saves[i]?`${new Date(saves[i]!.date).toLocaleString('ko-KR')} · 동료 ${saves[i]!.dogs}마리`:'이 칸에 현재 모험을 저장할 수 있어요.'}</p>{overwrite===i&&<p className="overwrite-note">기존 저장을 현재 모험으로 바꿉니다. 다시 누르면 저장돼요.</p>}</div><div className="slot-actions"><button onClick={()=>manualSave(i)}><Save size={15}/>{overwrite===i?'덮어쓰기 확인':'저장'}</button><button disabled={!saves[i]} onClick={()=>loadSave(i)}><FolderOpen size={15}/>불러오기</button></div></div>)}</div><div className="file-actions"><button onClick={exportSave}><Download size={19}/><span>파일로 저장<small>다른 기기로 가져갈 수 있어요</small></span></button><button onClick={()=>inputFile.current?.click()}><Upload size={19}/><span>저장 파일 열기<small>이전에 저장한 JSON 파일</small></span></button></div><p className="save-explainer"><Check size={14}/>탐험 중 15초마다 자동 저장됩니다. 브라우저 데이터를 지우기 전에는 파일로 보관하세요.</p></>}
 {panel==='shop'&&<div className="shop-items">{Object.entries(ITEMS).map(([id,item])=><div className="shop-item" key={id}><span>{item.icon}</span><div><h3>{item.name}</h3><p>{item.desc}</p><small>보유 {countItem(state,id)}개</small></div><button className="primary-button" disabled={state.coins<item.price} onClick={()=>dispatch({type:'buy',id})}>◈ {item.price}<small>1개 구입</small></button></div>)}<div className="shop-note"><Package size={18}/>보급 상자에서도 아이템과 코인을 찾을 수 있어요.</div></div>}
 {panel==='help'&&<div className="help-content"><div className="help-row"><kbd>W A S D / ↑ ↓ ← →</kbd><span>이동 · 길 클릭으로도 이동할 수 있어요.</span></div><div className="help-row"><kbd>Shift</kbd><span>누르고 있으면 달립니다.</span></div><div className="help-row"><kbd>E</kbd><span>가까운 강아지, 악당, 상점, 쉼터와 상호작용</span></div><div className="help-row"><kbd>B / M / P / J</kbd><span>가방 / 지도 / 동료 / 모험 일지</span></div><div className="help-row"><kbd>Esc</kbd><span>창 닫기 · 탐험으로 돌아가기</span></div><div className="help-tips"><h3>모험의 작은 요령</h3><p>강아지는 친구 간식 하나로 영입할 수 있어요. 함께할 동료를 바꾸면 새로운 친구가 뒤따라옵니다.</p><p>전투에서 공격과 기술, 아이템, 동료 교체는 한 턴을 사용합니다. 고유 기술은 두 번의 다른 행동 뒤에 다시 쓸 수 있어요.</p><p>쉼터는 모든 동료를 무료로 회복해 줍니다. 모두 쓰러지면 코인의 10%를 잃고 시작 지역 쉼터로 돌아옵니다.</p><p>길 끝의 빛나는 출구로 다음 지역에 갈 수 있어요. 한번 방문한 지역은 세계 지도에서 바로 이동할 수 있습니다.</p><p>모바일에서는 화면의 방향 버튼이나 길을 터치해 이동하세요.</p></div></div>}
 </DialogContent></Dialog><input ref={inputFile} type="file" accept=".json,application/json" hidden onChange={e=>void importSave(e.target.files?.[0])}/>
 </main>;
}
