'use client';
import {useEffect,useRef,type RefObject} from 'react';
import {SIZE,REGIONS,walkable,entities,bagRoom,type GameState,type Action} from '@/lib/game/model';
import {DOG_WALK_SHEETS} from '@/lib/game/dog-art';
import {advanceMotion,idleMotion} from '@/lib/game/motion';
import {render,type View} from '@/lib/game/render';
export default function World({game,paused,onAction,onTick,zoom,running}:{game:RefObject<GameState>;paused:RefObject<boolean>;onAction:(a:Action)=>void;onTick:()=>void;zoom:number;running:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);const zoomRef=useRef(zoom);zoomRef.current=zoom;const runningRef=useRef(running);runningRef.current=running;
 useEffect(()=>{const el=canvas.current!;const c=el.getContext('2d')!;const maps=REGIONS.map(region=>{const image=new Image();image.src=`/art/regions/${region.id}.png`;return image;}),sprites=new Image(),poodle=new Image(),interior=new Image(),entrance=new Image(),playerWalk=new Image(),enemies=new Image();const dogWalk=DOG_WALK_SHEETS.map(src=>{const image=new Image();image.src=src;return image;});enemies.src='/art/enemies.png';playerWalk.src='/art/player-walk.png';interior.src='/art/shop-interior.png';entrance.src='/art/shop-entrance.png';sprites.src='/art/sprites.png';poodle.src='/art/richi-poodle.png';let w=900,h=600,frame=0,last=0,lastUI=0,lastSecond=0,lastPlace=game.current.region+':'+game.current.place,lastParty=game.current.party.join(','),steps=0,lastPickup=0;let path:{x:number;y:number}[]=[];let interactId:string|null=null;
 const v:View={width:w,height:h,zoom:zoomRef.current,cx:game.current.x,cy:game.current.y,petX:game.current.x-52,petY:game.current.y+44,target:null,walking:false,playerMotion:idleMotion(),petMotion:idleMotion(),secondPetX:game.current.x-75,secondPetY:game.current.y+100,secondMotion:idleMotion(),dropSeen:new Map()};
 const resize=()=>{const r=el.getBoundingClientRect();w=r.width;h=r.height;const dpr=Math.min(window.devicePixelRatio||1,3);el.width=w*dpr;el.height=h*dpr;c.setTransform(dpr,0,0,dpr,0,0);v.width=w;v.height=h;};const ro=new ResizeObserver(resize);ro.observe(el);resize();
 function blur(){path=[];v.target=null;}
 function click(e:PointerEvent){if(paused.current)return;e.preventDefault();el.focus();const rect=el.getBoundingClientRect();const x=(e.clientX-rect.left-w/2)/v.zoom+v.cx,y=(e.clientY-rect.top-h/2)/v.zoom+v.cy;const ent=entities(game.current).find(a=>Math.hypot(a.x-x,a.y-20-y)<70);if(ent&&Math.hypot(game.current.x-ent.x,game.current.y-ent.y)<105){onAction({type:'interact',id:ent.id});return;}interactId=ent?.id||null;const goal=ent?{x:ent.x,y:ent.y+38}:{x,y};path=findPath(game.current,goal);v.target=path.length?path[path.length-1]:null;}
 window.addEventListener('blur',blur);el.addEventListener('pointerdown',click);
 function tick(time:number){const dt=Math.min((time-last)/1000||0,.04);last=time;const s=game.current;v.zoom=s.place==='shop'?Math.min(zoomRef.current,.5):zoomRef.current;
 if(lastPlace!==s.region+':'+s.place||Math.hypot(s.x-v.cx,s.y-v.cy)>1100){lastPlace=s.region+':'+s.place;v.cx=s.x;v.cy=s.y;v.petX=s.x-40;v.petY=s.y+50;v.playerMotion=idleMotion();v.petMotion=idleMotion();v.secondPetX=s.x-70;v.secondPetY=s.y+100;v.secondMotion=idleMotion();path=[];v.target=null;}
 if(lastParty!==s.party.join(',')){lastParty=s.party.join(',');v.petX=s.x-40;v.petY=s.y+50;v.secondPetX=s.x-70;v.secondPetY=s.y+100;v.petMotion=idleMotion();v.secondMotion=idleMotion();}
 if(!paused.current&&!s.battle){let dx=0,dy=0,remaining=Infinity;if(path.length){const p=path[0];const distance=Math.hypot(p.x-s.x,p.y-s.y);remaining=distance;if(distance<7){path.shift();if(!path.length){v.target=null;if(interactId){onAction({type:'interact',id:interactId});interactId=null;}}}else{dx=(p.x-s.x)/distance;dy=(p.y-s.y)/distance;}}
 const len=Math.hypot(dx,dy),speed=runningRef.current?365:235,oldX=s.x,oldY=s.y;
 if(len){const step=Math.min(speed*dt,remaining);dx=dx/len*step;dy=dy/len*step;if(walkable(s.x+dx,s.y,s.region,s.place))s.x+=dx;if(walkable(s.x,s.y+dy,s.region,s.place))s.y+=dy;}
 const traveled=Math.hypot(s.x-oldX,s.y-oldY);v.playerMotion=advanceMotion(v.playerMotion,s.x-oldX,s.y-oldY);v.walking=v.playerMotion.moving;
 steps+=traveled;if(steps>36){s.steps+=Math.floor(steps/36);steps%=36;}
 const oldPetX=v.petX,oldPetY=v.petY,pd=Math.hypot(s.x-v.petX,s.y-v.petY);
 if(pd>59){const follow=Math.min(1,dt*8);v.petX+=(s.x-v.petX)*(1-53/pd)*follow;v.petY+=(s.y-v.petY)*(1-53/pd)*follow;}
 v.petMotion=advanceMotion(v.petMotion,v.petX-oldPetX,v.petY-oldPetY);
 const secondX=v.secondPetX,secondY=v.secondPetY,sd=Math.hypot(v.petX-secondX,v.petY-secondY);if(s.party.length>1&&sd>62){const follow=Math.min(1,dt*8);v.secondPetX+=(v.petX-secondX)*(1-56/sd)*follow;v.secondPetY+=(v.petY-secondY)*(1-56/sd)*follow;}v.secondMotion=advanceMotion(v.secondMotion,v.secondPetX-secondX,v.secondPetY-secondY);
 const edge=(s.region===5?s.y<850:s.y<62)?0:s.x>SIZE-62?1:s.y>SIZE-62?2:s.x<62?3:-1;if(s.place==='field'&&edge>=0){const nr=REGIONS[s.region].neighbors[edge];if(nr>=0)onAction({type:'travel',region:nr,gate:true,edge});}
 if(time-lastSecond>1000){s.seconds++;lastSecond=time;}
 if(s.place==='field'&&s.region!==1&&s.seconds>=s.encounterGraceUntil&&game.current===s){const enemy=entities(s).find(e=>e.kind==='enemy'&&!e.captain&&Math.hypot(e.x-s.x,e.y-s.y)<55);if(enemy){path=[];v.target=null;interactId=null;onAction({type:'interact',id:enemy.id});}}

 if(s.place==='field'&&game.current===s&&time-lastPickup>450){const drop=s.drops.find(d=>d.region===s.region&&Math.hypot(d.x-s.x,d.y-s.y)<=90&&time-(v.dropSeen.get(d.id)??time)>1100&&bagRoom(s,d.item)>0);if(drop){lastPickup=time;onAction({type:'pickup'});}}
 }else{v.walking=false;v.playerMotion=advanceMotion(v.playerMotion,0,0);v.petMotion=advanceMotion(v.petMotion,0,0);v.secondMotion=advanceMotion(v.secondMotion,0,0);path=[];v.target=null;}
 const visibleW=w/v.zoom,visibleH=h/v.zoom;const cx=Math.max(visibleW/2,Math.min(SIZE-visibleW/2,s.x)),cy=Math.max(visibleH/2,Math.min(SIZE-visibleH/2,s.y));v.cx+=(cx-v.cx)*Math.min(1,dt*8);v.cy+=(cy-v.cy)*Math.min(1,dt*8);render(c,game.current,v,{maps,sprites,poodle,interior,entrance,playerWalk,dogWalk,enemies},time);if(time-lastUI>250){onTick();lastUI=time;}frame=requestAnimationFrame(tick);
 }frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('blur',blur);el.removeEventListener('pointerdown',click);};
 },[game,paused,onAction,onTick]);
 return <canvas ref={canvas} tabIndex={0} aria-label="가고 싶은 길을 터치해 이동합니다. 강아지, 악당, 상점, 전리품을 터치하면 다가가 상호작용합니다."/>;
}
function findPath(s:GameState,goal:{x:number;y:number}){const unit=32,N=64,key=(x:number,y:number)=>y*N+x;const sx=Math.floor(s.x/unit),sy=Math.floor(s.y/unit);let gx=Math.max(0,Math.min(63,Math.floor(goal.x/unit))),gy=Math.max(0,Math.min(63,Math.floor(goal.y/unit)));let best=Infinity;const originalX=gx,originalY=gy;for(let y=Math.max(0,originalY-4);y<=Math.min(63,originalY+4);y++)for(let x=Math.max(0,originalX-4);x<=Math.min(63,originalX+4);x++)if(walkable(x*unit+16,y*unit+16,s.region,s.place)){const dist=Math.hypot(x*unit+16-goal.x,y*unit+16-goal.y);if(dist<best){best=dist;gx=x;gy=y;}}const target=key(gx,gy),start=key(sx,sy);const queue=[start],parents=new Map<number,number>([[start,-1]]);let found=false;for(let i=0;i<queue.length;i++){const id=queue[i];if(id===target){found=true;break;}const x=id%N,y=Math.floor(id/N);for(const [dx,dy]of [[0,1],[0,-1],[1,0],[-1,0]]){const nx=x+dx,ny=y+dy,n=key(nx,ny);if(nx>=0&&nx<N&&ny>=0&&ny<N&&!parents.has(n)&&walkable(nx*unit+16,ny*unit+16,s.region,s.place)){parents.set(n,id);queue.push(n);}}}if(!found)return [];const result=[];for(let p=target;p!==start&&p!==-1;p=parents.get(p)??-1)result.unshift({x:(p%N)*unit+16,y:Math.floor(p/N)*unit+16});return result;}
