'use client';
import {useEffect,useRef,type RefObject} from 'react';
import {SIZE,REGIONS,walkable,nearest,entities,type GameState,type Action} from '@/lib/game/model';
import {render,type View} from '@/lib/game/render';
export default function World({game,paused,onAction,onTick,zoom,moveKeys}:{game:RefObject<GameState>;paused:RefObject<boolean>;onAction:(a:Action)=>void;onTick:()=>void;zoom:number;moveKeys:RefObject<Set<string>>}){
 const canvas=useRef<HTMLCanvasElement>(null);const zoomRef=useRef(zoom);zoomRef.current=zoom;
 useEffect(()=>{const el=canvas.current!;const c=el.getContext('2d')!;const maps=REGIONS.map(region=>{const image=new Image();image.src=`/art/regions/${region.id}.png`;return image;}),sprites=new Image(),poodle=new Image(),interior=new Image(),entrance=new Image();interior.src='/art/shop-interior.png';entrance.src='/art/shop-entrance.png';sprites.src='/art/sprites.png';poodle.src='/art/richi-poodle.png';const keys=moveKeys.current;let w=900,h=600,frame=0,last=0,lastUI=0,lastSecond=0,lastPlace=game.current.region+':'+game.current.place,steps=0;let path:{x:number;y:number}[]=[];let interactId:string|null=null;
 const v:View={width:w,height:h,zoom:zoomRef.current,cx:game.current.x,cy:game.current.y,petX:game.current.x-52,petY:game.current.y+44,target:null,walking:false};
 const resize=()=>{const r=el.getBoundingClientRect();w=r.width;h=r.height;const dpr=Math.min(window.devicePixelRatio||1,3);el.width=w*dpr;el.height=h*dpr;c.setTransform(dpr,0,0,dpr,0,0);v.width=w;v.height=h;};const ro=new ResizeObserver(resize);ro.observe(el);resize();
 function down(e:KeyboardEvent){if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName))return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift','e'].includes(key)){if(paused.current)return;e.preventDefault();keys.add(key);if(key==='e'&&!e.repeat){const n=nearest(game.current);if(n)onAction({type:'interact',id:n.id});}}}function up(e:KeyboardEvent){keys.delete(e.key.toLowerCase());}function blur(){keys.clear();path=[];v.target=null;}
 function click(e:PointerEvent){if(paused.current)return;el.focus();const rect=el.getBoundingClientRect();const x=(e.clientX-rect.left-w/2)/v.zoom+v.cx,y=(e.clientY-rect.top-h/2)/v.zoom+v.cy;const ent=entities(game.current).find(a=>Math.hypot(a.x-x,a.y-20-y)<70);if(ent&&Math.hypot(game.current.x-ent.x,game.current.y-ent.y)<105){onAction({type:'interact',id:ent.id});return;}interactId=ent?.id||null;const goal=ent?{x:ent.x,y:ent.y+38}:{x,y};path=findPath(game.current,goal);v.target=path.length?path[path.length-1]:null;}
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);el.addEventListener('pointerdown',click);
 function tick(time:number){const dt=Math.min((time-last)/1000||0,.04);last=time;const s=game.current;v.zoom=s.place==='shop'?Math.min(zoomRef.current,.5):zoomRef.current;
 if(lastPlace!==s.region+':'+s.place||Math.hypot(s.x-v.cx,s.y-v.cy)>1100){lastPlace=s.region+':'+s.place;v.cx=s.x;v.cy=s.y;v.petX=s.x-40;v.petY=s.y+50;path=[];v.target=null;keys.clear();}
 if(!paused.current&&!s.battle){let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft'));let dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));if(dx||dy){path=[];v.target=null;interactId=null;}else if(path.length){const p=path[0];const distance=Math.hypot(p.x-s.x,p.y-s.y);if(distance<7){path.shift();if(!path.length){v.target=null;if(interactId){onAction({type:'interact',id:interactId});interactId=null;}}}else{dx=(p.x-s.x)/distance;dy=(p.y-s.y)/distance;}}
 const len=Math.hypot(dx,dy),speed=keys.has('shift')?365:235;v.walking=len>0;if(len){dx=dx/len*speed*dt;dy=dy/len*speed*dt;let moved=false;if(walkable(s.x+dx,s.y,s.region,s.place)){s.x+=dx;moved=true;}if(walkable(s.x,s.y+dy,s.region,s.place)){s.y+=dy;moved=true;}if(moved){steps+=Math.hypot(dx,dy);if(steps>36){s.steps++;steps=0;}}}
 const pd=Math.hypot(s.x-v.petX,s.y-v.petY);if(pd>57){const follow=Math.min(1,dt*7);v.petX+=(s.x-v.petX)*(1-54/pd)*follow;v.petY+=(s.y-v.petY)*(1-54/pd)*follow;}
 const edge=(s.region===5?s.y<850:s.y<62)?0:s.x>SIZE-62?1:s.y>SIZE-62?2:s.x<62?3:-1;if(s.place==='field'&&edge>=0){const nr=REGIONS[s.region].neighbors[edge];if(nr>=0)onAction({type:'travel',region:nr,gate:true,edge});}
 if(time-lastSecond>1000){s.seconds++;lastSecond=time;}
 if(s.place==='field'&&s.region!==1&&s.seconds>=s.encounterGraceUntil&&game.current===s){const enemy=entities(s).find(e=>e.kind==='enemy'&&!e.captain&&Math.hypot(e.x-s.x,e.y-s.y)<55);if(enemy){path=[];v.target=null;interactId=null;onAction({type:'interact',id:enemy.id});}}
 }else{v.walking=false;keys.clear();}
 const visibleW=w/v.zoom,visibleH=h/v.zoom;const cx=Math.max(visibleW/2,Math.min(SIZE-visibleW/2,s.x)),cy=Math.max(visibleH/2,Math.min(SIZE-visibleH/2,s.y));v.cx+=(cx-v.cx)*Math.min(1,dt*8);v.cy+=(cy-v.cy)*Math.min(1,dt*8);render(c,s,v,{maps,sprites,poodle,interior,entrance},time);if(time-lastUI>250){onTick();lastUI=time;}frame=requestAnimationFrame(tick);
 }frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);el.removeEventListener('pointerdown',click);keys.clear();};
 },[game,paused,onAction,onTick,moveKeys]);
 return <canvas ref={canvas} tabIndex={0} aria-label="솔빛시 탐험. WASD 또는 방향키로 이동, E로 상호작용, Shift로 달리기. 길을 클릭해서 이동할 수도 있습니다."/>;
}
function findPath(s:GameState,goal:{x:number;y:number}){const unit=32,N=64,key=(x:number,y:number)=>y*N+x;const sx=Math.floor(s.x/unit),sy=Math.floor(s.y/unit);let gx=Math.max(0,Math.min(63,Math.floor(goal.x/unit))),gy=Math.max(0,Math.min(63,Math.floor(goal.y/unit)));let best=Infinity;const originalX=gx,originalY=gy;for(let y=Math.max(0,originalY-4);y<=Math.min(63,originalY+4);y++)for(let x=Math.max(0,originalX-4);x<=Math.min(63,originalX+4);x++)if(walkable(x*unit+16,y*unit+16,s.region,s.place)){const dist=Math.hypot(x*unit+16-goal.x,y*unit+16-goal.y);if(dist<best){best=dist;gx=x;gy=y;}}const target=key(gx,gy),start=key(sx,sy);const queue=[start],parents=new Map<number,number>([[start,-1]]);let found=false;for(let i=0;i<queue.length;i++){const id=queue[i];if(id===target){found=true;break;}const x=id%N,y=Math.floor(id/N);for(const [dx,dy]of [[0,1],[0,-1],[1,0],[-1,0]]){const nx=x+dx,ny=y+dy,n=key(nx,ny);if(nx>=0&&nx<N&&ny>=0&&ny<N&&!parents.has(n)&&walkable(nx*unit+16,ny*unit+16,s.region,s.place)){parents.set(n,id);queue.push(n);}}}if(!found)return [];const result=[];for(let p=target;p!==start&&p!==-1;p=parents.get(p)??-1)result.unshift({x:(p%N)*unit+16,y:Math.floor(p/N)*unit+16});return result;}
