import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,act,entities,walkable,packSave,unpackSave,currentDog,putItem,countItem,REGIONS,type GameState,type Entity} from './model.ts';
function closeTo(s:GameState,e:Entity){if(walkable(e.x,e.y,s.region)){s.x=e.x;s.y=e.y;return;}for(let y=e.y-85;y<=e.y+85;y+=8)for(let x=e.x-85;x<=e.x+85;x+=8)if(walkable(x,y,s.region)&&Math.hypot(x-e.x,y-e.y)<100){s.x=x;s.y=y;return;}throw Error(`Unreachable: ${e.id}`);}
test('25 slots, growth by five, maximum100, coins charged exactly once',()=>{let s=newGame();assert.equal(s.bag.length,25);s=act(s,{type:'expand'}).state;assert.equal(s.capacity,30);assert.equal(s.coins,120);assert.equal(act(s,{type:'expand'}).state.capacity,30);s.coins=100000;while(s.capacity<100)s=act(s,{type:'expand'}).state;assert.equal(act(s,{type:'expand'}).state.capacity,100);assert.equal(s.bag.length,100);});
test('full bag cannot partially consume loot or coins',()=>{let s=newGame();s.bag=Array.from({length:25},()=>({item:'berry',qty:9}));const e=entities(s).find(e=>e.kind==='loot')!;closeTo(s,e);const r=act(s,{type:'interact',id:e.id});assert.equal(r.state.coins,s.coins);assert.equal(r.state.looted.length,0);assert.equal(putItem(s,'potion',2),false);});
test('recruiting consumes exactly one treat and cannot duplicate dogs',()=>{let s=newGame();const e=entities(s).find(e=>e.kind==='dog')!;closeTo(s,e);s=act(s,{type:'interact',id:e.id}).state;assert.equal(s.dogs.length,2);assert.equal(countItem(s,'treat'),4);s=act(s,{type:'interact',id:e.id}).state;assert.equal(s.dogs.length,2);s=act(s,{type:'switch',id:e.id}).state;assert.equal(currentDog(s).name,e.name);});
test('no treat denies recruitment without mutation',()=>{const s=newGame();s.bag=s.bag.map(v=>v?.item==='treat'?null:v);const e=entities(s).find(e=>e.kind==='dog')!;closeTo(s,e);assert.equal(act(s,{type:'interact',id:e.id}).state.dogs.length,1);});
test('save restores inventory, expansion, companions, location, progression',()=>{let s=newGame();s=act(s,{type:'expand'}).state;s.visited.push(1);s.region=1;s.x=1024;s.y=1600;s.defeated.push('enemy-0-0');assert.deepEqual(unpackSave(packSave(s)),s);s.region=0;s.x=1170;s.y=1070;assert.ok(walkable(s.x,s.y,0));assert.equal(unpackSave(packSave(s)).x,1170);});
test('malformed and oversized saves are rejected',()=>{assert.throws(()=>unpackSave('not json'));assert.throws(()=>unpackSave('x'.repeat(200001)));for(const patch of [{capacity:999},{coins:-1},{dogs:[]},{x:NaN},{region:80},{active:'missing'},{bag:[{item:'bad',qty:2}]},{recruited:['<bad>']}]){const s={...newGame(),...patch};assert.throws(()=>unpackSave(JSON.stringify({game:'tails-city',state:s})));}});
test('all region entities are reachable from walkable ground',()=>{for(let region=0;region<6;region++){const s=newGame();s.region=region;for(const e of entities(s))closeTo(s,e);}});
test('all six regions connected; travel only through correct gates or discovered shortcuts',()=>{let s=newGame();assert.equal(act(s,{type:'travel',region:5}).state.region,0);s.x=2000;s.y=970;s=act(s,{type:'travel',region:1,gate:true}).state;assert.equal(s.region,1);assert.equal(s.x,80);assert.equal(act(s,{type:'travel',region:0}).state.region,0);const found=new Set([0]),queue=[0];for(const id of queue)for(const n of REGIONS[id].neighbors)if(n>=0&&!found.has(n)){found.add(n);queue.push(n);}assert.equal(found.size,6);s.region=2;s.x=1024;s.y=2000;s=act(s,{type:'travel',region:5,gate:true}).state;assert.equal(s.region,5);assert.equal(s.y,970);s.y=840;s=act(s,{type:'travel',region:2,gate:true}).state;assert.equal(s.region,2);});
test('combat awards one reward and skill cooldown is enforced',()=>{let s=newGame();const e=entities(s).find(e=>e.kind==='enemy')!;closeTo(s,e);s=act(s,{type:'interact',id:e.id}).state;assert.ok(s.battle);const coins=s.coins;s=act(s,{type:'skill'}).state;if(s.battle){const hp=s.battle.enemy.hp;s=act(s,{type:'skill'}).state;assert.equal(s.battle!.enemy.hp,hp);s=act(s,{type:'attack'}).state;}assert.equal(s.battle,null);assert.equal(s.coins,coins+55);assert.equal(s.defeated.filter(id=>id===e.id).length,1);assert.equal(act(s,{type:'attack'}).state.coins,s.coins);});
test('items consume a combat turn; rest revives whole party for free',()=>{let s=newGame();currentDog(s).hp=10;s=act(s,{type:'item',id:'potion'}).state;assert.equal(currentDog(s).hp,55);assert.equal(countItem(s,'potion'),3);const e=entities(s).find(e=>e.kind==='rest')!;closeTo(s,e);s=act(s,{type:'interact',id:e.id}).state;assert.equal(currentDog(s).hp,currentDog(s).maxHp);assert.equal(s.coins,320);});
test('losing has a recoverable checkpoint and flee ends combat',()=>{let s=newGame();const e=entities(s).find(e=>e.kind==='enemy')!;closeTo(s,e);s=act(s,{type:'interact',id:e.id}).state;currentDog(s).hp=1;s=act(s,{type:'attack'}).state;assert.equal(s.battle,null);assert.equal(s.region,0);assert.equal(s.coins,288);assert.equal(currentDog(s).hp,currentDog(s).maxHp);closeTo(s,e);s=act(s,{type:'interact',id:e.id}).state;s=act(s,{type:'flee'}).state;assert.equal(s.battle,null);});
test('complete six-region campaign can be won with starter and earned rewards',()=>{let s=newGame();s.region=5;let e=entities(s).find(e=>e.captain)!;closeTo(s,e);assert.equal(act(s,{type:'interact',id:e.id}).state.battle,null);s.region=0;for(let region=0;region<6;region++){s.region=region;if(!s.visited.includes(region))s.visited.push(region);for(const id of [`enemy-${region}-0`,`enemy-${region}-1`,`captain-${region}`]){const rest=entities(s).find(e=>e.kind==='rest')!;closeTo(s,rest);s=act(s,{type:'interact',id:rest.id}).state;const enemy=entities(s).find(e=>e.id===id)!;closeTo(s,enemy);s=act(s,{type:'interact',id}).state;assert.ok(s.battle);let turns=0;while(s.battle&&turns++<30){const dog=currentDog(s);if(dog.hp<35&&countItem(s,'revive'))s=act(s,{type:'item',id:'revive'}).state;else if(dog.hp<35&&countItem(s,'potion'))s=act(s,{type:'item',id:'potion'}).state;else s=act(s,{type:s.battle.cooldown===0?'skill':'attack'}).state;}assert.ok(s.defeated.includes(id),`${id} defeated with ${currentDog(s).hp} HP`);}}assert.equal(s.won,true);assert.equal(s.defeated.length,18);assert.equal(unpackSave(packSave(s)).won,true);});
