import {SIZE,REGIONS,BREEDS,entities,currentDog,nearest,type GameState} from './model';
export type View={width:number;height:number;zoom:number;cx:number;cy:number;petX:number;petY:number;target:{x:number;y:number}|null;walking:boolean};
export type Art={maps:HTMLImageElement;sprites:HTMLImageElement};
export function sprite(ctx:CanvasRenderingContext2D,img:HTMLImageElement,index:number,x:number,y:number,height:number,flip=false){if(!img.complete||!img.naturalWidth)return;const cw=img.naturalWidth/4,ch=img.naturalHeight/2;const width=height*.75;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(img,index%4*cw,Math.floor(index/4)*ch,cw,ch,-width/2,-height*.83,width,height);ctx.restore();}
function label(c:CanvasRenderingContext2D,text:string,x:number,y:number,color='#fffdeb',bg='#294932db'){c.font='600 12px Arial';const w=c.measureText(text).width+18;c.fillStyle=bg;c.beginPath();c.roundRect(x-w/2,y-12,w,23,6);c.fill();c.fillStyle=color;c.textAlign='center';c.fillText(text,x,y+4);}
export function render(c:CanvasRenderingContext2D,s:GameState,v:View,art:Art,t:number){const {width:w,height:h,zoom:z}=v;c.clearRect(0,0,w,h);const tx=w/2-v.cx*z,ty=h/2-v.cy*z;const screen=(x:number,y:number)=>({x:x*z+tx,y:y*z+ty});c.imageSmoothingEnabled=false;c.fillStyle='#78996b';c.fillRect(0,0,w,h);
 if(art.maps.complete&&art.maps.naturalWidth){const cell=art.maps.naturalWidth/3;c.drawImage(art.maps,s.region%3*cell,Math.floor(s.region/3)*cell,cell,cell,tx,ty,SIZE*z,SIZE*z);}
 const near=nearest(s);const all=entities(s);const at=[...all.map(e=>({kind:'entity',y:e.y,e})),{kind:'pet',y:v.petY},{kind:'player',y:s.y}].sort((a,b)=>a.y-b.y);
 // Destination indicator and navigational markers are functional overlays.
 if(v.target){const p=screen(v.target.x,v.target.y);c.strokeStyle='#f6e99b';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y,10,5,0,0,7);c.stroke();}
 for(const entry of at){if(entry.kind==='entity'&&'e'in entry){const e=entry.e!;const p=screen(e.x,e.y);if(p.x< -100||p.x>w+100||p.y< -100||p.y>h+100)continue;
 if(e.kind==='dog'||e.kind==='enemy'){c.fillStyle='#172f3029';c.beginPath();c.ellipse(p.x,p.y,18*z,7*z,0,0,7);c.fill();sprite(c,art.sprites,e.kind==='dog'?BREEDS[e.breed!].sprite:7,p.x,p.y,94*z);label(c,e.name,p.x,p.y+20,e.kind==='enemy'?'#ffe9df':'#fffdeb',e.kind==='enemy'?'#703d38e8':'#386653e8');const bounce=Math.sin(t*.002+e.x)*3;label(c,e.kind==='dog'?'♥':e.captain?'★':'!',p.x,p.y-75*z+bounce,e.kind==='dog'?'#af533b':'#fff2d9',e.kind==='dog'?'#fff6ddd9':'#bd6752ed');}
 else {const icon=e.kind==='shop'?'🛍️':e.kind==='rest'?'⛺':'🎒';c.font=`${32*z}px Arial`;c.textAlign='center';c.fillText(icon,p.x,p.y);label(c,e.name,p.x,p.y+21);}
 if(near?.id===e.id){c.strokeStyle='#fff8ce';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y,26*z,10*z,0,0,Math.PI*2);c.stroke();}
 }else if(entry.kind==='player'){const p=screen(s.x,s.y);c.fillStyle='#27392c33';c.beginPath();c.ellipse(p.x,p.y,16*z,6*z,0,0,7);c.fill();sprite(c,art.sprites,0,p.x,p.y+(v.walking?Math.sin(t*.016)*2:0),110*z);label(c,'나',p.x,p.y+19,'#315143','#fffbedef');}
 else if(entry.kind==='pet'){const p=screen(v.petX,v.petY);sprite(c,art.sprites,BREEDS[currentDog(s).breed].sprite,p.x,p.y+(v.walking?Math.sin(t*.02)*2:0),81*z);label(c,currentDog(s).name,p.x,p.y+18,'#fff4d5','#8a6945df');}}
 const gates=[{x:1024,y:s.region===5?850:70},{x:1978,y:970},{x:1024,y:1978},{x:70,y:970}];REGIONS[s.region].neighbors.forEach((id,i)=>{if(id<0)return;const p=screen(gates[i].x,gates[i].y);c.strokeStyle='#ffffc899';c.lineWidth=3;c.beginPath();c.arc(p.x,p.y,22+Math.sin(t*.003)*3,0,7);c.stroke();label(c,`${['↑','→','↓','←'][i]} ${REGIONS[id].name}`,p.x,p.y-37,'#fff8de','#2c4c3ce8');});
 // Local map thumbnail with live position.
 const mw=132,mx=w-mw-16,my=h-mw-40;if(w>500&&art.maps.complete&&art.maps.naturalWidth){c.fillStyle='#fffdecf2';c.beginPath();c.roundRect(mx-4,my-4,mw+8,mw+28,8);c.fill();const cell=art.maps.naturalWidth/3;c.drawImage(art.maps,s.region%3*cell,Math.floor(s.region/3)*cell,cell,cell,mx,my,mw,mw);c.fillStyle='#f6e798';c.strokeStyle='#294d3e';c.lineWidth=2;c.beginPath();c.arc(mx+s.x/SIZE*mw,my+s.y/SIZE*mw,4,0,7);c.fill();c.stroke();c.fillStyle='#647557';c.font='10px Arial';c.textAlign='center';c.fillText('현재 위치',mx+mw/2,my+mw+16);}
}
