import {SIZE,REGIONS,BREEDS,ITEMS,WEAPONS,entities,currentDog,nearest,enemyStats,type GameState} from './model';
import {walkFrame,type WalkMotion} from './motion';
export type View={width:number;height:number;zoom:number;cx:number;cy:number;petX:number;petY:number;target:{x:number;y:number}|null;walking:boolean;playerMotion:WalkMotion;petMotion:WalkMotion;dropSeen:Map<string,number>};
export type Art={maps:HTMLImageElement[];sprites:HTMLImageElement;poodle:HTMLImageElement;interior:HTMLImageElement;entrance:HTMLImageElement;playerWalk:HTMLImageElement;richiWalk:HTMLImageElement};
export function sprite(ctx:CanvasRenderingContext2D,img:HTMLImageElement,index:number,x:number,y:number,height:number,flip=false,standalone?:HTMLImageElement){if(index===8){if(!standalone?.complete||!standalone.naturalWidth)return;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(standalone,-height*.375,-height*.83,height*.75,height);ctx.restore();return;}if(!img.complete||!img.naturalWidth)return;const cw=img.naturalWidth/4,ch=img.naturalHeight/2;const width=height*.75;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(img,index%4*cw,Math.floor(index/4)*ch,cw,ch,-width/2,-height*.83,width,height);ctx.restore();}
function animatedSprite(c:CanvasRenderingContext2D,sheet:HTMLImageElement,x:number,y:number,height:number,motion:WalkMotion,stride=24){
 if(!sheet.complete||!sheet.naturalWidth)return false;
 const cw=sheet.naturalWidth/4,ch=sheet.naturalHeight/4,frame=walkFrame(motion,stride);
 c.drawImage(sheet,frame*cw,motion.facing*ch,cw,ch,x-height/2,y-height*.82,height,height);
 return true;
}
function label(c:CanvasRenderingContext2D,text:string,x:number,y:number,color='#fffdeb',bg='#294932db'){c.font='600 12px Arial';const w=c.measureText(text).width+18;c.fillStyle=bg;c.beginPath();c.roundRect(x-w/2,y-12,w,23,6);c.fill();c.fillStyle=color;c.textAlign='center';c.fillText(text,x,y+4);}
export function render(c:CanvasRenderingContext2D,s:GameState,v:View,art:Art,t:number){const {width:w,height:h,zoom:z}=v;const indoors=s.place==='shop';const map=indoors?art.interior:art.maps[s.region];const frames=[[1150,1172],[1254,1254],[1254,1254],[1200,1170],[1254,1180],[1240,1212]];const [fw,fh]=indoors?[1254,1254]:frames[s.region];c.clearRect(0,0,w,h);const tx=w/2-v.cx*z,ty=h/2-v.cy*z;const screen=(x:number,y:number)=>({x:x*z+tx,y:y*z+ty});c.imageSmoothingEnabled=false;c.fillStyle='#78996b';c.fillRect(0,0,w,h);
 if(map.complete&&map.naturalWidth){ c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(map,0,0,map.naturalWidth*fw/1254,map.naturalHeight*fh/1254,tx,ty,SIZE*z,SIZE*z);c.imageSmoothingEnabled=false;}
 if(v.dropSeen.size>600){const ids=new Set(s.drops.map(d=>d.id));for(const id of v.dropSeen.keys())if(!ids.has(id))v.dropSeen.delete(id);}
 const near=nearest(s);const all=entities(s);const at=[...all.map(e=>({kind:'entity',y:e.y,e})),{kind:'pet',y:v.petY},{kind:'player',y:s.y}].sort((a,b)=>a.y-b.y);
 // Destination indicator and navigational markers are functional overlays.
 if(v.target){const p=screen(v.target.x,v.target.y);c.strokeStyle='#f6e99b';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y,10,5,0,0,7);c.stroke();}
 for(const entry of at){if(entry.kind==='entity'&&'e'in entry){const e=entry.e!;const p=screen(e.x,e.y);if(p.x< -100||p.x>w+100||p.y< -100||p.y>h+100)continue;
 if(e.kind==='drop'){const drop=s.drops.find(d=>d.id===e.id)!;if(!v.dropSeen.has(e.id))v.dropSeen.set(e.id,drop.createdAt<s.seconds-2?t-1500:t);const age=t-v.dropSeen.get(e.id)!,progress=Math.min(1,age/800),ease=1-(1-progress)**3;const origin=screen(drop.originX,drop.originY),px=origin.x+(p.x-origin.x)*ease,py=origin.y+(p.y-origin.y)*ease-Math.sin(progress*Math.PI)*65*z;const bob=progress===1?Math.sin(t*.004+e.x)*2:0;c.save();c.shadowColor=WEAPONS[e.item!]?'#ffd26e':'#fff2a6';c.shadowBlur=14;c.fillStyle=WEAPONS[e.item!]?'#e5b34855':'#fff3b044';c.beginPath();c.ellipse(p.x,p.y,20*z,9*z,0,0,7);c.fill();c.shadowBlur=0;c.font=`${Math.max(21,34*z)}px Arial`;c.textAlign='center';c.fillText(ITEMS[e.item!].icon,px,py-7*z+bob);c.font='bold 10px Arial';c.strokeStyle='#293b31';c.lineWidth=3;c.strokeText(`×${e.qty}`,px+13*z,py+4);c.fillStyle='#fffbe6';c.fillText(`×${e.qty}`,px+13*z,py+4);c.restore();}
 else if(e.kind==='dog'||e.kind==='enemy'){c.fillStyle='#172f3029';c.beginPath();c.ellipse(p.x,p.y,18*z,7*z,0,0,7);c.fill();sprite(c,art.sprites,e.kind==='dog'?BREEDS[e.breed!].sprite:7,p.x,p.y,94*z);label(c,e.name,p.x,p.y+20,e.kind==='enemy'?'#ffe9df':'#fffdeb',e.kind==='enemy'?'#703d38e8':'#386653e8');const bounce=Math.sin(t*.002+e.x)*3;label(c,e.kind==='dog'?'♥':e.captain?'★':'!',p.x,p.y-75*z+bounce,e.kind==='dog'?'#af533b':'#fff2d9',e.kind==='dog'?'#fff6ddd9':'#bd6752ed');if(e.kind==='enemy'){const enemy=enemyStats(s,e),bw=Math.max(54,76*z),by=p.y-108*z;c.fillStyle='#302b2ce8';c.beginPath();c.roundRect(p.x-bw/2-2,by-2,bw+4,18,4);c.fill();c.fillStyle='#5d3739';c.fillRect(p.x-bw/2,by,bw,5);c.fillStyle=e.captain?'#e9a35f':'#e16c6c';c.fillRect(p.x-bw/2,by,bw*enemy.hp/enemy.maxHp,5);c.font='bold 9px Arial';c.fillStyle='#fff5e2';c.textAlign='center';c.fillText(`${enemy.hp} / ${enemy.maxHp}`,p.x,by+14); }}
 else if(e.kind==='shop'){if(art.entrance.complete&&art.entrance.naturalWidth){const frame=art.entrance.naturalWidth/2;c.drawImage(art.entrance,0,0,frame,art.entrance.naturalHeight,p.x-85*z,p.y-131*z,170*z,170*z);}label(c,'상점 입구',p.x,p.y+34);}
 else if(e.kind==='merchant'||e.kind==='exit'){label(c,e.kind==='merchant'?'상인 미로 · 포션 / 무기':'↓ 밖으로 나가기',p.x,p.y-28,'#fff4d6','#61472de8');}
 else {const icon=e.kind==='rest'?'⛺':'🎒';c.font=`${32*z}px Arial`;c.textAlign='center';c.fillText(icon,p.x,p.y);label(c,e.name,p.x,p.y+21);}
 if(near?.id===e.id){c.strokeStyle='#fff8ce';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y,26*z,10*z,0,0,Math.PI*2);c.stroke();}
 }else if(entry.kind==='player'){const p=screen(s.x,s.y);c.fillStyle='#27392c33';c.beginPath();c.ellipse(p.x,p.y,16*z,6*z,0,0,7);c.fill();if(!animatedSprite(c,art.playerWalk,p.x,p.y,110*z,v.playerMotion))sprite(c,art.sprites,0,p.x,p.y,110*z);label(c,'나',p.x,p.y+19,'#315143','#fffbedef');}
 else if(entry.kind==='pet'){const p=screen(v.petX,v.petY);const breed=BREEDS[currentDog(s).breed];if(breed.sprite!==8||!animatedSprite(c,art.richiWalk,p.x,p.y,86*z,v.petMotion,19))sprite(c,art.sprites,breed.sprite,p.x,p.y+(v.petMotion.moving?Math.sin(v.petMotion.distance*.18)*2:0),81*z,v.petMotion.facing===1,art.poodle);label(c,currentDog(s).name,p.x,p.y+18,'#fff4d5','#8a6945df');}}
 const gates=[{x:1024,y:s.region===5?850:70},{x:1978,y:970},{x:1024,y:1978},{x:70,y:970}];if(!indoors)REGIONS[s.region].neighbors.forEach((id,i)=>{if(id<0)return;const p=screen(gates[i].x,gates[i].y);c.strokeStyle='#ffffc899';c.lineWidth=3;c.beginPath();c.arc(p.x,p.y,22+Math.sin(t*.003)*3,0,7);c.stroke();label(c,`${['↑','→','↓','←'][i]} ${REGIONS[id].name}`,p.x,p.y-37,'#fff8de','#2c4c3ce8');});
 // Local map thumbnail with live position.
 const mw=132,mx=w-mw-16,my=h-mw-40;if(w>500&&map.complete&&map.naturalWidth){c.fillStyle='#fffdecf2';c.beginPath();c.roundRect(mx-4,my-4,mw+8,mw+28,8);c.fill(); c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(map,0,0,map.naturalWidth*fw/1254,map.naturalHeight*fh/1254,mx,my,mw,mw);c.imageSmoothingEnabled=false;c.fillStyle='#f6e798';c.strokeStyle='#294d3e';c.lineWidth=2;c.beginPath();c.arc(mx+s.x/SIZE*mw,my+s.y/SIZE*mw,4,0,7);c.fill();c.stroke();c.fillStyle='#647557';c.font='10px Arial';c.textAlign='center';c.fillText('현재 위치',mx+mw/2,my+mw+16);}
}
